// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: product.service.proto

package service

import (
	context "context"
	dto "github.com/recommendation/services/core/application/product/dto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetProductDetail(ctx context.Context, in *dto.GetProductDetailReq, opts ...grpc.CallOption) (*dto.GetProductDetailResp, error)
	GetRecommendationForUser(ctx context.Context, in *dto.GetRecommendationForUserReq, opts ...grpc.CallOption) (*dto.GetRecommendationForUserResp, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProductDetail(ctx context.Context, in *dto.GetProductDetailReq, opts ...grpc.CallOption) (*dto.GetProductDetailResp, error) {
	out := new(dto.GetProductDetailResp)
	err := c.cc.Invoke(ctx, "/service.ProductService/GetProductDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetRecommendationForUser(ctx context.Context, in *dto.GetRecommendationForUserReq, opts ...grpc.CallOption) (*dto.GetRecommendationForUserResp, error) {
	out := new(dto.GetRecommendationForUserResp)
	err := c.cc.Invoke(ctx, "/service.ProductService/GetRecommendationForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility
type ProductServiceServer interface {
	GetProductDetail(context.Context, *dto.GetProductDetailReq) (*dto.GetProductDetailResp, error)
	GetRecommendationForUser(context.Context, *dto.GetRecommendationForUserReq) (*dto.GetRecommendationForUserResp, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (UnimplementedProductServiceServer) GetProductDetail(context.Context, *dto.GetProductDetailReq) (*dto.GetProductDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductDetail not implemented")
}
func (UnimplementedProductServiceServer) GetRecommendationForUser(context.Context, *dto.GetRecommendationForUserReq) (*dto.GetRecommendationForUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendationForUser not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetProductDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ProductService/GetProductDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductDetail(ctx, req.(*dto.GetProductDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetRecommendationForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.GetRecommendationForUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetRecommendationForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ProductService/GetRecommendationForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetRecommendationForUser(ctx, req.(*dto.GetRecommendationForUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductDetail",
			Handler:    _ProductService_GetProductDetail_Handler,
		},
		{
			MethodName: "GetRecommendationForUser",
			Handler:    _ProductService_GetRecommendationForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.service.proto",
}
