// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: product.dto.proto

package dto

import (
	model "github.com/recommendation/services/core/application/product/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewProductReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // TODO change user_id to header, detect from bearer token
	ProductIds []int32 `protobuf:"varint,2,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
}

func (x *ViewProductReq) Reset() {
	*x = ViewProductReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_dto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewProductReq) ProtoMessage() {}

func (x *ViewProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_dto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewProductReq.ProtoReflect.Descriptor instead.
func (*ViewProductReq) Descriptor() ([]byte, []int) {
	return file_product_dto_proto_rawDescGZIP(), []int{0}
}

func (x *ViewProductReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ViewProductReq) GetProductIds() []int32 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type ViewProductResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListProduct []*model.Product `protobuf:"bytes,1,rep,name=list_product,json=listProduct,proto3" json:"list_product,omitempty"`
}

func (x *ViewProductResp) Reset() {
	*x = ViewProductResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_product_dto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewProductResp) ProtoMessage() {}

func (x *ViewProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_dto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewProductResp.ProtoReflect.Descriptor instead.
func (*ViewProductResp) Descriptor() ([]byte, []int) {
	return file_product_dto_proto_rawDescGZIP(), []int{1}
}

func (x *ViewProductResp) GetListProduct() []*model.Product {
	if x != nil {
		return x.ListProduct
	}
	return nil
}

var File_product_dto_proto protoreflect.FileDescriptor

var file_product_dto_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x74, 0x6f, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x0e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x73, 0x22, 0x44, 0x0a, 0x0f, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_product_dto_proto_rawDescOnce sync.Once
	file_product_dto_proto_rawDescData = file_product_dto_proto_rawDesc
)

func file_product_dto_proto_rawDescGZIP() []byte {
	file_product_dto_proto_rawDescOnce.Do(func() {
		file_product_dto_proto_rawDescData = protoimpl.X.CompressGZIP(file_product_dto_proto_rawDescData)
	})
	return file_product_dto_proto_rawDescData
}

var file_product_dto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_product_dto_proto_goTypes = []interface{}{
	(*ViewProductReq)(nil),  // 0: dto.ViewProductReq
	(*ViewProductResp)(nil), // 1: dto.ViewProductResp
	(*model.Product)(nil),   // 2: model.Product
}
var file_product_dto_proto_depIdxs = []int32{
	2, // 0: dto.ViewProductResp.list_product:type_name -> model.Product
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_product_dto_proto_init() }
func file_product_dto_proto_init() {
	if File_product_dto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_product_dto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewProductReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_product_dto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewProductResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_product_dto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_dto_proto_goTypes,
		DependencyIndexes: file_product_dto_proto_depIdxs,
		MessageInfos:      file_product_dto_proto_msgTypes,
	}.Build()
	File_product_dto_proto = out.File
	file_product_dto_proto_rawDesc = nil
	file_product_dto_proto_goTypes = nil
	file_product_dto_proto_depIdxs = nil
}
